@echo on
setlocal

set "PROJECT_DIR=C:\Users\fossato\PycharmProjects\checker"
set "VENV_DIR=%PROJECT_DIR%\.venv"
set "SITE_PACKAGES=%VENV_DIR%\Lib\site-packages"
set "ENTRY_POINT=%PROJECT_DIR%\main.py"
set "VERSION_FILE=%PROJECT_DIR%\_version.py"
set "EXE_NAME=checker"

call "%VENV_DIR%\Scripts\activate.bat" || goto :fail

:: ── Verifica che shared_lib esista in site-packages ──────────────────────────
if not exist "%SITE_PACKAGES%\shared_lib" (
    echo ERRORE: shared_lib non trovata in %SITE_PACKAGES%
    echo Esegui: pip install shared_lib oppure pip install -e .
    goto :fail
)

:: ── Genera _version.py con la versione git corrente ──────────────────────────
echo Lettura versione da git...
cd /d "%PROJECT_DIR%"
for /f "delims=" %%v in ('git describe --tags --dirty --always 2^>nul') do set "GIT_VERSION=%%v"

if "%GIT_VERSION%"=="" (
    echo ATTENZIONE: git describe fallito, uso "dev"
    set "GIT_VERSION=dev"
)

echo Versione rilevata: %GIT_VERSION%
(
    echo # Auto-generated by build_checker_to_exe.bat - DO NOT EDIT
    echo __version__ = "%GIT_VERSION%"
) > "%VERSION_FILE%"
echo _version.py scritto.

:: ── Elimina spec precedente per evitare conflitti con --add-data ─────────────
if exist "%PROJECT_DIR%\%EXE_NAME%.spec" (
    echo Rimuovo spec precedente...
    del "%PROJECT_DIR%\%EXE_NAME%.spec"
)

:: ── Build PyInstaller ─────────────────────────────────────────────────────────
pyinstaller --noconfirm --clean --onefile --windowed ^
  --name="%EXE_NAME%" ^
  --icon="%PROJECT_DIR%\checker.ico" ^
  --add-data="%SITE_PACKAGES%\shared_lib;shared_lib" ^
  --add-data="%PROJECT_DIR%\ui_status_bar.py;." ^
  --add-data="%PROJECT_DIR%\config.csv;." ^
  --add-data="%VERSION_FILE%;." ^
  --hidden-import=winrt ^
  --hidden-import=winrt.windows.foundation.collections ^
  "%ENTRY_POINT%" || goto :fail

:: ── Rinomina l'exe aggiungendo la versione: checker_v0.1.0.exe ───────────────
set "FINAL_EXE=%PROJECT_DIR%\dist\%EXE_NAME%_%GIT_VERSION%.exe"
rename "%PROJECT_DIR%\dist\%EXE_NAME%.exe" "%EXE_NAME%_%GIT_VERSION%.exe"

:: ── Pulizia _version.py dalla cartella sorgente ──────────────────────────────
del "%VERSION_FILE%"

echo.
echo OK - EXE in: %FINAL_EXE%
echo Versione inclusa: %GIT_VERSION%
goto :end

:fail
echo.
echo ERRORE durante il build.
:end
pause
endlocal