@echo on
setlocal

set "PROJECT_DIR=C:\Users\fossato\PycharmProjects\checker"
set "VENV_DIR=%PROJECT_DIR%\.venv"
set "ENTRY_POINT=%PROJECT_DIR%\main.py"
set "VERSION_FILE=%PROJECT_DIR%\_version.py"
set "EXE_NAME=checker"

call "%VENV_DIR%\Scripts\activate.bat" || goto :fail

:: ── Genera _version.py con la versione git corrente ──────────────────────────
echo Lettura versione da git...
cd /d "%PROJECT_DIR%"
for /f "delims=" %%v in ('git describe --tags --dirty --always 2^>nul') do set "GIT_VERSION=%%v"

if "%GIT_VERSION%"=="" (
    echo ATTENZIONE: git describe fallito, uso "dev"
    set "GIT_VERSION=dev"
)

echo Versione rilevata: %GIT_VERSION%
(
    echo # Auto-generated by build_checker_to_exe.bat - DO NOT EDIT
    echo __version__ = "%GIT_VERSION%"
) > "%VERSION_FILE%"
echo _version.py scritto.

:: ── Build PyInstaller ─────────────────────────────────────────────────────────
pyinstaller --noconfirm --onefile --windowed ^
  --name="%EXE_NAME%" ^
  --icon="%PROJECT_DIR%\checker.ico" ^
  --add-data="%PROJECT_DIR%\shared_lib;shared_lib" ^
  --add-data="%PROJECT_DIR%\config.csv;." ^
  --add-data="%VERSION_FILE%;." ^
  --hidden-import=winrt ^
  --hidden-import=winrt.windows.foundation.collections ^
  "%ENTRY_POINT%" || goto :fail

:: ── Pulizia: rimuove _version.py dalla cartella sorgente dopo il build ────────
del "%VERSION_FILE%"

echo.
echo OK - EXE in: %PROJECT_DIR%\dist\%EXE_NAME%.exe
echo Versione inclusa: %GIT_VERSION%
goto :end

:fail
echo.
echo ERRORE durante il build.
:end
pause
endlocal